### ISSUE TITLE
Compatibility with e.g. 500px.com

### ISSUE THREAD

**Issue by grahamperrin** [lunu-bounir/allow-right-click.html#1]
Hi

Not working with images at `500px.com` … tricky, I imagine. Beyond the scope of this extension?

Thanks

**Comment by lunu-bounir** [comment]
Should have been fixed! Please reopen if not!

**Comment by grahamperrin** [comment]
Sorry, still not working for me. 

Tested with Waterfox 56.2.2 (below requirements) and Firefox 61.0.2 on FreeBSD-CURRENT.

**Comment by lunu-bounir** [comment]
Please try 0.1.5 and report back.
